### ISSUE TITLE
不能跳過進站畫面

### ISSUE THREAD

**Issue by adern9** [eight04/ptt-mail-backup#8]
輸入帳號密碼以後，就拋出exception了，用兩個帳號測試都一樣。

**Comment by eight04** [comment]
錯誤訊息？

**Comment by adern9** [comment]
C:\>ptt-mail-backup -d 2018-06-12 --all
User: adern9
Password:
Traceback (most recent call last):
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hankv4\AppData\Local\Programs\Python\Python37\Scripts\ptt-mail-backup.exe\__main__.py", line 9, in <module>
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\ptt_mail_backup\__init__.py", line 64, in main
    with ptt_login(args.user, args.password) as bot:
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\ptt_mail_backup\ptt_bot.py", line 46, in ptt_login
    bot.login(user, password)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\ptt_mail_backup\ptt_bot.py", line 97, in login
    self.unt(self.detect("主功能表", 0), on_data=handle_after_login)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\ptt_mail_backup\ptt_bot.py", line 121, in unt
    data = self.channel.recv(math.inf)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

**Comment by eight04** [comment]
在命令列加上 `-v` 選項後的結果呢？可以取得更詳細的訊息

**Comment by adern9** [comment]
C:\>ptt-mail-backup -d 2018-06-12 -v --all
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.9p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
User: adern9
Password:
INFO:ptt_mail_backup.ptt_bot:start login
INFO:ptt_mail_backup.ptt_bot:adern9 login success
INFO:ptt_mail_backup.ptt_bot:uncaught error, here is the last screen:
                -----===== 本日十大熱門話題 =====-----

  1. 看板 : GambleGhost     《 Aug 13 23:03:59 》  57 篇     AyaMatsuura
     標題 : 年輕帥氣的熊把拔生日快樂！！！！！
  2. 看板 : Gossiping       《 Aug 13 20:38:07 》  39 篇        sheng612
     標題 : [爆卦] 洪慈庸退出時代力量 1620記者會
  3. 看板 : talk            《 Aug 13 22:52:01 》  37 篇     hcc19880512
     標題 : 這裡是充滿愛與閃光的偷可板
  4. 看板 : HatePolitics    《 Aug 13 15:01:39 》  37 篇         genheit
     標題 : [討論]柯定調蔡衍明是愛台灣
  5. 看板 : Gossiping       《 Aug 13 20:39:36 》  34 篇     TwoSeam5566
     標題 : [新聞] 柯文哲表態挺郭台銘　酸韓國瑜：把國民黨
  6. 看板 : Gossiping       《 Aug 13 18:53:09 》  32 篇     ButterMyAss
     標題 : [新聞] 爆旺中原本挺他 柯P：中國代理人要我講
  7. 看板 : Wanted          《 Aug 13 22:42:50 》  30 篇         js85059
     標題 : [問安]
  8. 看板 : Hate            《 Aug 13 22:37:13 》  19 篇     charliechao
     標題 : [黑特]
  9. 看板 : Hate            《 Aug 13 21:12:35 》  18 篇        lin91223
     標題 :
 10. 看板 : Gossiping       《 Aug 13 21:17:01 》  17 篇              A6
     標題 : [新聞] 民進黨中執會通過 林昶佐、洪慈庸兩選區

  瀏覽 第 1/1 頁 (100%)  目前顯示: 第 01~22 行              (h)說明 (←/q)離開
Traceback (most recent call last):
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hankv4\AppData\Local\Programs\Python\Python37\Scripts\ptt-mail-backup.exe\__main__.py", line 9, in <module>
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\ptt_mail_backup\__init__.py", line 64, in main
    with ptt_login(args.user, args.password) as bot:
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\ptt_mail_backup\ptt_bot.py", line 46, in ptt_login
    bot.login(user, password)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\ptt_mail_backup\ptt_bot.py", line 97, in login
    self.unt(self.detect("主功能表", 0), on_data=handle_after_login)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\ptt_mail_backup\ptt_bot.py", line 121, in unt
    data = self.channel.recv(math.inf)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

**Comment by eight04** [comment]
目前程式不會跳過進站畫面，在修好前請先把進站畫面關掉︰

1. 在主功能表，進入個人設定區
2. 選擇進站畫面
3. 把所有選項切成 X

**Comment by adern9** [comment]
把進站畫面關閉以後可以進入信箱了，但仍然無法下載信件，會在 #9 內說明。

**Comment by eight04** [comment]
這個 bug 還沒被修好前，不要關閉
