### ISSUE TITLE
無法讀取包含控制碼的文章

### ISSUE THREAD

**Issue by adern9** [eight04/ptt-mail-backup#9]
```
C:\>ptt-mail-backup -d 2018-06-12 -v --all
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.9p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
User: adern9
Password:
INFO:ptt_mail_backup.ptt_bot:start login
INFO:ptt_mail_backup.ptt_bot:adern9 login success
INFO:ptt_mail_backup.ptt_bot:enter main menu
Login success, try entering your mail box
INFO:ptt_mail_backup.ptt_bot:get in the mail box
INFO:ptt_mail_backup.ptt_bot:get last index
INFO:ptt_mail_backup.ptt_bot:get last index success: 200
Fetching mail: 1
INFO:ptt_mail_backup.ptt_bot:get 1th article
INFO:ptt_mail_backup.ptt_bot:title: [註冊成功囉]
INFO:ptt_mail_backup.ptt_bot:uncaught error, here is the last screen:
        ╔═╮╔═╮╭═╮
        ╠═╮╠═╮╰═╮ EMail認證通過
◇──  ╚═╯╚═╯╰═╯────────────────────────◇

      嗨嗨，adern9你好：
      歡迎加入 ptt的行列 ^o^
      若還不能Post請重新login一次 ^_^ (要換身份囉)

      祝      使用愉快
      記得常常來玩喔.... ^_^

                                                        站長~~
◇────────────────────────────────────◇
★新最愛 請用 m來設定「我的最愛」
★新設定 Ptt 提供個人化設定, 請至 (U)ser->(I)nfo->(C)ustomize
★新新聞 Ptt 和聯合新聞網合作, 您可至 udnnews板看每日最新新聞
★新個人 歡迎至批踢踢兔申請個人板 (telnet://ptt2.cc)






  瀏覽 第 1/1 頁 (100%)  ▲此頁內容會依閱讀者不同,原文未必有您的資料 (←q)離開
Traceback (most recent call last):
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hankv4\AppData\Local\Programs\Python\Python37\Scripts\ptt-mail-backup.exe\__main__.py", line 9, in <module>
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\ptt_mail_backup\__init__.py", line 83, in main
    article = bot.get_article(i)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\ptt_mail_backup\ptt_bot.py", line 225, in get_article
    self.unt(self.on_col(0), on_data=handle_animated)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\ptt_mail_backup\ptt_bot.py", line 121, in unt
    data = self.channel.recv(math.inf)
  File "c:\users\hankv4\appdata\local\programs\python\python37\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout
```

**Comment by eight04** [comment]
控制碼警告擋住了目前行數的顯示……所以無法偵測目前在第幾行。這有點麻煩，因為這樣程式就不知道目前是在哪一行/頁。
